[package]
name = "peer"
version = "0.0.3"
edition = "2021"

[dependencies]
clap = { version = "4.5.16", features = ["derive"] }

async-std = { version = "1.12.0", features = ["attributes"] }
async-trait = "0.1"
futures = "0.3"
