[package]
name = "peer"
version = "0.1.0"
edition = "2021"

[dependencies]
async-std = { version = "1.12", features = ["attributes"] }
async-trait = "0.1"
clap = { version = "4.5", features = ["derive"] }
futures = "0.3"
chrono = "0.4"
