[package]
name = "peer"
version = "0.0.1"
edition = "2021"

[dependencies]
clap = { version = "4.5", features = ["derive"] }
async-std = { version = "1.12", features = ["attributes"] }
futures = "0.3"
