[package]
name = "peer"
version = "0.1.1"
edition = "2021"

[dependencies]
clap = { version = "4.5", features = ["derive"] }
async-std = { version = "1.12", features = ["attributes"] }
async-trait = "0.1"
futures = "0.3"
chrono = "0.4"
anyhow = "1.0"
